### ISSUE TITLE
test.php

### ISSUE THREAD

**Issue by BeZazz** [kevinlekiller/simple_php_yenc_decode#2]
When I ran test.php

The output was
PHP Warning:  file_get_contents(yEnc.zip.yEnc): failed to open stream: No such file or directory in /home/nZEDb/www/example/test.php on line 3
The yEnc decode was successful, you can now unzip yEnc.zip and run the html file in a browser to verify the result.
(It was not successful)

On the 3rd line I had to put the full path to yEnc.zip.yEnc

**Comment by kevinlekiller** [comment]
Should be good now.
